### ISSUE TITLE
How to correctly handle Optionals wrapped in other polymorphic types?

### ISSUE THREAD

**Issue by fakeh** [FasterXML/jackson-datatype-jdk8#19]
Hi,
Thanks for this module, I'm looking forward to starting to use Optionals within my code!

I have a problem illustrated by the following example, which results in a ClassCastException being thrown. This is because OptionalSerializer (and presumably also the deserializer) assume that any @JsonTypeInfo applies to the value of the Optional rather than the property holding the Optional (see de/serializeWithType methods).

```
import java.io.IOException;
import java.util.Date;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;

public class NestedOptionalTest {
	private static ObjectMapper mapper;
	
	static {
		mapper = new ObjectMapper();
		mapper.registerModule(new Jdk8Module());
	}
	
	public static void main(String[] args) throws IOException {
		Holder<Date> holder = new Holder<Date>();
		holder.setValue(new Date());
		
		String json = mapper.writeValueAsString(holder);
		System.out.println(json);
		
		@SuppressWarnings("unchecked")
		Holder<Double> out = mapper.readValue(json, Holder.class);
		System.out.println(out.getValue());
		
		Holder<Optional<Date>> optionalHolder = new Holder<Optional<Date>>();
		optionalHolder.setValue(Optional.of(new Date()));
		
		json = mapper.writeValueAsString(optionalHolder);
		System.out.println(json);
		
		@SuppressWarnings("unchecked")
		Holder<Optional<Double>> optionalOut = mapper.readValue(json, Holder.class);
		Optional<Double> optionalDouble = optionalOut.getValue();
		System.out.println(optionalDouble);
	}
	
	private static class Holder<T> {
		private T value;
		
		@JsonTypeInfo(use=Id.CLASS, include=As.WRAPPER_OBJECT) 
		public T getValue(){
			return value;
		}
		public void setValue(T value){
			this.value = value;
		}
	}
}
```

@cowtowncoder Is there a way to correctly handle this scenario? I've successfully got the Optional holder to serialize for my case by adding calls to typeSer.writeTypePrefix/SuffixForScalar into serializeWithType, but I couldn't figure out the deserialization.

Many thanks, Dan.

**Comment by cowtowncoder** [comment]
As a general rule, I would simply recommend against trying to use generic class as root values.
This is usually more common with `Map`s and `Collection`s, but same applies to `Optional` as well.
Further, combination of generics on polymorphic handling is problematic: latter relies on type-erased types, and generic type information can not be retained.

However, in this particular case, genericity may not be the main problem, but rather application of polymorphic handling, like you state.
This is being improved for 2.7 (and 2.6 had better support than 2.5), making `Optional` first a `ReferenceType` (added in 2.6), and second of all, making reference types work semantically similar to 1-element collections -- meaning that `@JsonTypeInfo` would indeed relate to content value, not optional wrapper itself.

However... I am not optimistic about your case. The problem really is that combination. If value was declared as `Optional`, it could and should work. But if base type is essentially just `Object`, I don't think this can necessarily be made to work.

**Comment by cowtowncoder** [comment]
One other thing to note: make sure to try this with 2.7.0-SNAPSHOT (from `master` branch that is), to see how things are working -- implementation was heavily rewritten since 2.6, and part of that did have to do with polymorphic type handling, which was indeed incorrectly handled. There were other fixes related to inclusion, filtering as well.

**Comment by fakeh** [comment]
I will revisit the issue as soon as I am able to get back to that project.

**Comment by cowtowncoder** [comment]
@faked Version `2.7.0-rc2` is out via Maven Central, as well, and it has all the fixes to both `Optional` handling, and improved generic type resolution.

**Comment by cowtowncoder** [comment]
Assuming things are fixed; may be reopened with a reproduction if not.

**Comment by fakeh** [comment]
Hi cowtowncoder,

The example above still does not work with 2.7, though the exception changes:

````
{"value":{"java.util.Date":1454601817596}}
Thu Feb 04 16:03:37 GMT 2016
{"value":{"java.util.Optional":1454601817718}}
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class java.util.Optional] from Long integral number (1454601817718); no single-long-arg constructor/factory method
 at [Source: {"value":{"java.util.Optional":1454601817718}}; line: 1, column: 32] (through reference chain: entity.json.Holder["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:894)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromLong(StdValueInstantiator.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1168)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:146)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:115)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromAny(AsWrapperTypeDeserializer.java:64)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:554)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:488)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3788)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at entity.json.NestedOptionalTest.main(NestedOptionalTest.java:45)

**Comment by fakeh** [comment]
Note that whilst the example code tries to read in a Optional<Double>, I would of course prefer an Optional<Date>...

**Comment by cowtowncoder** [comment]
@fakeh Remaining problem is not with `Optional` handling, but in not passing full type to `readValue`. You can not use either:

    Holder<Double> out = mapper.readValue(json, Holder.class);
    Holder<Optional<Double>> optionalOut = mapper.readValue(json, Holder.class);   

because Java Type erasure will then only see type as `Holder<?>`.

Instead, you must specify type as something like:

    Holder<Double> out = mapper.readValue(json, new TypeRefefence<Holder<Double>>() { }

and so forth (or, use `TypeFactory` to programmatically constructed the structured type.

This is why I recommend NOT using generic types as the root value. They can be made to work, but are typically a big hassle as usage is non-obvious. Unfortunately the underlying Type Erasure is due to JVM/JDK and nothing Jackson can do much about.

**Comment by fakeh** [comment]
Aha, I should have added that I tried that, but the exception changes to:
````
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (VALUE_NUMBER_INT), expected START_OBJECT: need JSON Object to contain As.WRAPPER_OBJECT type information for class java.util.Date
 at [Source: {"value":{"java.util.Optional":1454674750241}}; line: 1, column: 32] (through reference chain: entity.json.Holder["value"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:962)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromScalar(AsWrapperTypeDeserializer.java:59)
	at com.fasterxml.jackson.databind.deser.std.StdScalarDeserializer.deserializeWithType(StdScalarDeserializer.java:26)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:91)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserialize(OptionalDeserializer.java:13)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer._deserialize(AsWrapperTypeDeserializer.java:115)
	at com.fasterxml.jackson.databind.jsontype.impl.AsWrapperTypeDeserializer.deserializeTypedFromAny(AsWrapperTypeDeserializer.java:64)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserializeWithType(OptionalDeserializer.java:114)
	at com.fasterxml.jackson.datatype.jdk8.OptionalDeserializer.deserializeWithType(OptionalDeserializer.java:13)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:488)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3788)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
	at entity.json.NestedOptionalTest.main(NestedOptionalTest.java:47)
````

Can you advise?

Best, Dan.

**Comment by fakeh** [comment]
By the way, if I do:
````
		Holder<Holder<Date>> holderHolder = new Holder<Holder<Date>>(new Holder<Date>(new Date()));
		String holderHolderJson = mapper.writeValueAsString(holderHolder);
		System.out.println(holderHolderJson);
		holderHolder = mapper.readValue(holderHolderJson, Holder.class);
		System.out.println(holderHolder.getValue().getValue());
````
It works, so it seems I can specify Holder.class and allow Jackson to figure out the typing for this case.

**Comment by cowtowncoder** [comment]
Ok. One more question: does this only fail for one of wrapped types (`Double` or `Date`), or both?
There is one additional oddity wrt `Double`, polymorphic typing: it is one of 4 "natural" types (along with `boolean`, `String` and `Long`) which can and do omit type. All other types (including `Date`) must have type information. Perhaps that could be related here.

On Type Erasure; a common work-around for root values is to specify "throw-away" types like:

    class DateHolder extends Holder<Date> { }

and use those. This gets around Type Erasure by binding generic type information through sub-classing: resulting type is not generic. I am guessing that would not necessarily be enough here but often it can simplify things, esp. if number of parameterizations used is small.

**Comment by fakeh** [comment]
Hi, see the full snippet:

````
import java.io.IOException;
import java.util.Date;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;

public class NestedOptionalTest {
	private static ObjectMapper mapper;
	
	static {
		mapper = new ObjectMapper();
		mapper.registerModule(new Jdk8Module());
	}
	
	public static void main(String[] args) throws IOException {
		Holder<Date> holder = new Holder<Date>(new Date());
		String json = mapper.writeValueAsString(holder);
		System.out.println(json); //Prints {"value":{"java.util.Date":1454688362534}} 
		
		@SuppressWarnings("unchecked")
		Holder<Double> out = mapper.readValue(json, Holder.class);
		System.out.println(out.getValue()); //Correctly prints date
		
		Holder<Holder<Date>> holderHolder = new Holder<Holder<Date>>(new Holder<Date>(new Date()));
		String holderHolderJson = mapper.writeValueAsString(holderHolder);
		System.out.println(holderHolderJson);
		holderHolder = mapper.readValue(holderHolderJson, Holder.class);
		System.out.println(holderHolder.getValue().getValue()); //Correctly prints Date
		

		Holder<Optional<Date>> optionalHolder = new Holder<Optional<Date>>();
		optionalHolder.setValue(Optional.of(new Date()));
		json = mapper.writeValueAsString(optionalHolder);
		System.out.println(json); //Prints {"value":{"java.util.Optional":1454688398337}}
		
		try{
			Holder<Optional<Date>> optionalOut = mapper.readValue(json, new TypeReference<Holder<Optional<Date>>>() {});
			Optional<Date> optionalDate = optionalOut.getValue();
			System.out.println(optionalDate);
		}catch(JsonMappingException e){
			//Prints:
			//Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (VALUE_NUMBER_INT), expected START_OBJECT: need JSON Object to contain As.WRAPPER_OBJECT type information for class java.util.Date
			 //at [Source: {"value":{"java.util.Optional":1454688398337}}; line: 1, column: 32] (through reference chain: entity.json.Holder["value"])
			e.printStackTrace();
		}
		
		Holder<Optional<Double>> optionalOut = mapper.readValue(json, new TypeReference<Holder<Optional<Double>>>() {});
		Optional<Double> optionalDouble = optionalOut.getValue();
		System.out.println(optionalDouble); //Success! Prints Optional[1.454688673343E12]
	}
	
	private static class Holder<T> {
		private T value;
		
		private Holder(){}
		private Holder(T value){
			setValue(value);
		}
		
		@JsonTypeInfo(use=Id.CLASS, include=As.WRAPPER_OBJECT) 
		public T getValue(){
			return value;
		}
		public void setValue(T value){
			this.value = value;
		}
	}
}
````

Putting the Holder<Optional<Date>> to Json and bringing it back to H<O<Date>> doesn't work, but because the JSON is "java.util.Optional":1234567234.0022, bringing it back as a H<O<Double>> works. But obviously, I should be able to get the date back, especially after specifying it with the TypeReference.

I hope that helps!
Dan.

**Comment by cowtowncoder** [comment]
Quick note: JSON serialization is wrong. When polymorphic handling is enabled, type information MUST be available. So deserializer is actually right: it is missing type info. That you are providing type parameters does not change this aspect, as definition forces use of type information for `value`, regardless of contextual information. I am not sure if that is what you intend or not, considering that you are explicitly providing type, and so it seems that perhaps `@JsonTypeInfo` here is superfluous.

This leads me to suggest that perhaps definition of Wrapper is not right: either `@JsonTypeInfo` should be dropped; or, alternatively, serialization side has issues. It could be that `Optional` handling is not adding information properly.

So perhaps there is a bug on serialization side of things. However, even here the Type Erasure is problematic: you are still not providing actual type information: output type is effectively `Holder<?>`.
And while runtime type is used for serializing fields, it is not used/usable for base type information for polymorphic types. It may be that using:

    ObjectWriter w = mapper.writerFor(new TypeReference<Holder<Optional<Data>>() { });
    String json = w.writeValueAsString(value);

would work better.

For what it is worth, use of `Double` for type during deserialization, at the end, is just a work-around that happens to work, because of "natural" types not requiring type information. It is not exactly working as planned, just happens to work for this combination of events.

In the end, I strongly recommend you to change things not to use generic types as root value; especially so when using `Optional` as part of the mix.

**Comment by fakeh** [comment]
I don't understand why Holder<Holder<Date>> is OK, but Holder<Optional<Date>> can't work?
Why can't I have serialisation that gives {value: { "java.util.Optional": { "java.util.Date": 1234567890 }}} (or something without the Optional part too).

**Comment by cowtowncoder** [comment]
@fakeh You may need to read more about Java Type Erasure if the explanation is not enough. Also keep in mind that Jackson tries to guarantee round-trip serialization: what it produces it can read. Not that any possible structure would be supported. Because JSON has no data/metadata distinction, all type/object ids must be included within regular data, and this makes it much more difficult to reason about what constitutes metadata (type id, object id), and what regular data to bind.

Anyway: at this point I have said all I can say -- when serializing generic type objects, you MUST provide full generic type information: and `Class` is NOT enough (or just instance). There is no way around that, and code as shown will not work and is not expected to work.

**Comment by fakeh** [comment]
I'm sorry to have caused offence, unless I'm misinterpreting the tone here. You've been very helpful and I sincerely appreciate it.

In the case of Holder<Holder<Date>> working, whilst Holder<Optional<Date>> does not, the difference is that the handling of Optional includes its type information but the Date then does not, e.g. `{"value":{"java.util.Optional":1455289826413}}`. This is why it can then be read as a Double, but not as a Date. I wonder if it would be possible to have the option to include type information for the parameterisation of the Optional somehow, by somehow passing the information from the @JavaTypeInfo?

Best, Dan.

**Comment by cowtowncoder** [comment]
@fakeh No offense taken. I can sometimes be (and esp. sound blunt), but I also did not mean this to be hostile response. :)

You are right in that the problem is with missing type information, and the challenge is in providing it. The reason I am closing this is just because fundamentally I do not see something to change here -- yes, there is the question from your side of either providing type information (perhaps with `mapper.writerFor(fullyGenericAwareJavaType)`) or by changing design to use a (non-generic) wrapper.

But without type information deserialization will not work, and that is a limitation we are keeping. 

So I think you should try out a way to get type information to be included in serialization.

Now... I may be wrong with respect to above. Perhaps problem has to do with _wrong_ type information being handled, or, perhaps, incomplete. There is another issue for figuring out a way to add generic (nested) type information.
Actually yes, I better re-open this. It's not as clear and cut as I thought for a bit.
Thank you for patience!

**Comment by fakeh** [comment]
I would see some way to configure the module to include type information in the JSON (the same information as @JsonTypeInfo configures) as a way to resolve this.
Dan.

**Comment by cowtowncoder** [comment]
2.7.4 will have a few fixes with respect to handling of polymorphic values for `Optional`, and these may help with this issue. So it would make sense to try either locally built 2.7.4-SNAPSHOT, or, within a week or so when official release done, actual 2.7.4.

**Comment by fakeh** [comment]
Thanks for the update. I will have a look again come 2.7.4.

**Comment by cowtowncoder** [comment]
Assuming problem is fixed in latest 2.7 (2.7.6) or 2.8[.1].
